### ISSUE TITLE
`mkdir` should be replaced with `dir.create`

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/rnaseq_demystified_workshop_2021#2]
https://github.com/umich-brcf-bioinf/2021-04-26-umich-rnaseqDemystified/blob/68a2afbead65c74a55fe53deec6f2f66a51ff0d0/Day2Rmds/Module06_DEAnalysisSetup.Rmd#L70

**Comment by rcavalcante** [comment]
Replace

```
mkdir("./data") 
```

with

```
dir.create("./data")
```

**Comment by dkcoxie** [comment]
Command has been updated
