### ISSUE TITLE
Comparison reference differs from previous code

### ISSUE THREAD

**Issue by rcavalcante** [umich-brcf-bioinf/rnaseq_demystified_workshop_2021#3]
https://github.com/umich-brcf-bioinf/2021-04-26-umich-rnaseqDemystified/blob/dc4586eb4ebb57cfe289cb9190efcbdf17671c09/Day2Rmds/Module10_DEComparisons.Rmd#L83

**Comment by rcavalcante** [comment]
Suggest changing 

```{r SetsResult}
Comparison <- "condition_Mov.KD_vs_Irrel"
res.KD <- results(dds, name=Comparison)
Comparison <- "condition_Mov.OE_vs_Irrel"
res.OE <- results(dds, name=Comparison)
```

to

```{r SetsResult}
Comparison <- "Gtype.Tx_wt.control_vs_ko.control"
resA <- results(dds, name=Comparison)
Comparison <- "Gtype.Tx_ko.Tx_vs_ko.control"
resB <- results(dds, name=Comparison)
```

Not sure what you'd want to call the results objects.

**Comment by rcavalcante** [comment]
Suggest changing

```{r AdditionalComparisons}
res <- results(dds, contrast=c("condition", "Mov.OE", "Mov.KD")) 
head(res)
```

to

```{r AdditionalComparisons}
res <- results(dds, contrast=c("Gtype.Tx", "ko.Tx", "wt.Tx")) 
head(res)
```

Check ordering because offhand I don't remember which is case and which is control.

**Comment by rcavalcante** [comment]
Fix reference to results in

```{r ResultsKD}
head(res.KD)
```

To match something from the above comment (i.e. `resA` or `resB`).

**Comment by dkcoxie** [comment]
Closing issue because I'm 90% sure these changes have been made. Please don't hesitate to generate a new issue if there are holdover references to Mov10 dataset/comparisons
